require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlandaysController do

  # This should return the minimal set of attributes required to create a valid
  # Planday. As you add validations to Planday, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "plan" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlandaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all plandays as @plandays" do
      planday = Planday.create! valid_attributes
      get :index, {}, valid_session
      assigns(:plandays).should eq([planday])
    end
  end

  describe "GET show" do
    it "assigns the requested planday as @planday" do
      planday = Planday.create! valid_attributes
      get :show, {:id => planday.to_param}, valid_session
      assigns(:planday).should eq(planday)
    end
  end

  describe "GET new" do
    it "assigns a new planday as @planday" do
      get :new, {}, valid_session
      assigns(:planday).should be_a_new(Planday)
    end
  end

  describe "GET edit" do
    it "assigns the requested planday as @planday" do
      planday = Planday.create! valid_attributes
      get :edit, {:id => planday.to_param}, valid_session
      assigns(:planday).should eq(planday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Planday" do
        expect {
          post :create, {:planday => valid_attributes}, valid_session
        }.to change(Planday, :count).by(1)
      end

      it "assigns a newly created planday as @planday" do
        post :create, {:planday => valid_attributes}, valid_session
        assigns(:planday).should be_a(Planday)
        assigns(:planday).should be_persisted
      end

      it "redirects to the created planday" do
        post :create, {:planday => valid_attributes}, valid_session
        response.should redirect_to(Planday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved planday as @planday" do
        # Trigger the behavior that occurs when invalid params are submitted
        Planday.any_instance.stub(:save).and_return(false)
        post :create, {:planday => { "plan" => "invalid value" }}, valid_session
        assigns(:planday).should be_a_new(Planday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Planday.any_instance.stub(:save).and_return(false)
        post :create, {:planday => { "plan" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested planday" do
        planday = Planday.create! valid_attributes
        # Assuming there are no other plandays in the database, this
        # specifies that the Planday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Planday.any_instance.should_receive(:update_attributes).with({ "plan" => "" })
        put :update, {:id => planday.to_param, :planday => { "plan" => "" }}, valid_session
      end

      it "assigns the requested planday as @planday" do
        planday = Planday.create! valid_attributes
        put :update, {:id => planday.to_param, :planday => valid_attributes}, valid_session
        assigns(:planday).should eq(planday)
      end

      it "redirects to the planday" do
        planday = Planday.create! valid_attributes
        put :update, {:id => planday.to_param, :planday => valid_attributes}, valid_session
        response.should redirect_to(planday)
      end
    end

    describe "with invalid params" do
      it "assigns the planday as @planday" do
        planday = Planday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Planday.any_instance.stub(:save).and_return(false)
        put :update, {:id => planday.to_param, :planday => { "plan" => "invalid value" }}, valid_session
        assigns(:planday).should eq(planday)
      end

      it "re-renders the 'edit' template" do
        planday = Planday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Planday.any_instance.stub(:save).and_return(false)
        put :update, {:id => planday.to_param, :planday => { "plan" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested planday" do
      planday = Planday.create! valid_attributes
      expect {
        delete :destroy, {:id => planday.to_param}, valid_session
      }.to change(Planday, :count).by(-1)
    end

    it "redirects to the plandays list" do
      planday = Planday.create! valid_attributes
      delete :destroy, {:id => planday.to_param}, valid_session
      response.should redirect_to(plandays_url)
    end
  end

end
